# Generated by Django 5.0.6 on 2024-06-09 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
