# Generated by Django 5.0.6 on 2024-06-09 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.CharField(max_length=20)),
                ('assigned_on', models.DateField(default=django.utils.timezone.now)),
                ('submitted_on', models.DateField(default='9999-12-31 23:59:59')),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
