# Generated by Django 5.0.6 on 2024-06-09 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted_on',
            field=models.DateTimeField(default='9999-12-31 23:59:59'),
        ),
    ]
