# Generated by Django 5.0.6 on 2024-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submitted_on',
            field=models.DateTimeField(default='9999-12-31T23:59:59'),
        ),
    ]
