# Generated by Django 5.0.6 on 2024-06-09 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_assignment_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc)),
        ),
    ]
